name = jackbase
description = Add discription here
preview = preview.png
template = jackbase-layout

; Regions
regions[navigation]       = Navigation bar
regions[branding]         = Branding
regions[header]           = Header
regions[webcaret_banner]  = Banner
regions[highlighted]      = Highlighted
regions[help]             = Help
regions[content]          = Content
regions[contentleft]      = Content-left
regions[contentcenter]    = Content-center
regions[contentright]     = Content-right
regions[sidebar_first]    = First sidebar
regions[sidebar_second]   = Second sidebar
regions[footer]          = Footer
regions[footer1]          = Footer1
regions[footer2]          = Footer2
regions[footer3]          = Footer3
regions[footer4]          = Footer4
regions[copy]             = Copy

; Stylesheets
stylesheets[all][] = css/layouts/jackbase/jackbase.layout.css
stylesheets[all][] = css/layouts/jackbase/jackbase.layout.no-query.css

; Scripts
scripts[] = layouts/jackbase/assets/off-canvas.js
