name = Off Canvas Jack
description = A layout demonstrating the off canvas responsive navigation pattern.
preview = preview.png
template = off-canvas-jack-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/off-canvas-jack/off-canvas-jack.layout.css

; Scripts
scripts[] = layouts/off-canvas-jack/assets/off-canvas.js
